name: pockettalk
description: PocketTalk - Mobile poker application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  web_socket_channel: ^3.0.2
  stomp_dart_client: ^2.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.3
  shared_preferences: ^2.3.4
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  equatable: ^2.0.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  mockito: ^5.4.5

flutter:
  generate: true
  uses-material-design: true
